-- 동일한 회원이 동일한 상품을 재구매한 데이터
-- 재구매한 회원 ID, 재구매상품ID
-- 회원ID ASC, 상품ID DESC

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC