-- 서울에 위치한
-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회
-- 리뷰는 평균점수 소수점 세번째 자리에서 반올림
-- 경과는 평균점수를 기준으로 내림차순 정렬 DESC, 즐겨찾기수 DESC

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS AVERAGE_SCORE
FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY AVERAGE_SCORE DESC, I.FAVORITES DESC