-- 주문정보 FIRST_HALF
-- PK FLAVOR

-- 아이스크림 성분 ICECREAM_INFO
-- PK FLAVOR

-- ICECREAM_INFO FLAVOR -> FIRST_HALF FLAVOR

-- 총주문량 3000이상 & 주성분과일 FLAVOR
-- 주문량 DESC

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I
    ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000
 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC